personal_type:
    - ["professeurs", "profs", "PRE01"]
    - ["charges_de_cours", "chargescours", "CC001"]

departments:
    - short_name: "aoti"
      long_name: "Analytique, Opérations et Technologies de l’Information (AOTI)"
      code: "2450"
    - short_name: "etudes-urb-touristiques"
      long_name: "Études Urbaines et Touristiques"
      code: "2310"
    - short_name: "finance"
      long_name: "Finance"
      code: "2040"
    - short_name: "management"
      long_name: "Management"
      code: "2440"
    - short_name: "marketing"
      long_name: "Marketing"
      code: "2390"
    - short_name: "org-ress-humaines"
      long_name: "Organisation et Ressources Humaines"
      code: "2013"
    - short_name: "sci-comptables"
      long_name: "Sciences Comptables"
      code: "2200"
    - short_name: "sci-economiques"
      long_name: "Sciences Économiques"
      code: "2070"
    - short_name: "strat-resp-soc-env"
      long_name: "Stratégie, Responsabilité Sociale et Environnementale"
      code: "2380"
    - short_name: "ecole-sup-mode"
      long_name: "École Supérieure de Mode"
      code: "1600"

modele: |
    *
    * Liste d'envoi des {TYPE_LONG}-esg-dept-{DEPT_SHORT}
    *
    *
    * .HH ON
    * Ack= Yes
    * Attachments= Yes
    * Auto-Delete= Yes,Semi-Auto,Delay(4),Max(6),Probe(30)
    * Change-Log= Yes
    * Confidential= Yes
    * Digest= Yes,Same,Monthly
    * Errors-To= Owners
    * Language= FRANCAIS
    * Loopcheck= NoSpam
    * Misc-Options= UTF8_HEADER
    * Notebook= Yes,/home/listserv/lists/archives/{TYPE_SHORT}-esg-dept-{DEPT_SHORT},Monthly
    * Notebook= Private
    * Notify= No
    * Owner= almora-diaz.xavier@uqam.ca
    * Reply-To= Sender,Respect
    * Review= Owner
    * Send= Owner
    * Send= Confirm
    * Sender= None
    * Service= *
    * Subject-Tag= "{TYPE_SHORT_UPPER}-ESG-DEPT-{DEPT_SHORT_UPPER}"
    * Subscription= By_Owner
    * Validate= No
    * .HH OFF
    *

chemins_de_fichier:
  entree: "listes"
  sortie: "files"





